### ISSUE TITLE
full screen games with resolution different from my screen's resolution open up with black bars on the bottom and the top.

### ISSUE THREAD

**Issue by ghost** [dylanaraps/sowm#16]
is it because there is no ewmh support?

if yes, i understand why you wouldn't want to include ewmh support, i could maybe write a patch(when i get the time). is implementing ewmh support hard?

if not, what can i do for my game(tf2) to scale correctly?

edit: minecraft seems to scale correctly, maybe it's tf2's fault. though it works fine on dwm

**Comment by dylanaraps** [comment]
I don't play or have any games installed on my system. I run `musl` as well so only few games will run if I try them. Is there an open source game I can compile so I can try and reproduce this issue? 

I don't know if this is EWMH related or not too. Try `catwm` (*which also has no support for EWMH*) to see if it occurs there as well. :+1:

**Comment by tjtf2** [comment]
I've tried it in catwm and it also didn't work.

I've also tried minecraft. Minecraft seemed to work fine both in windowed and in fullscreen mode.

One open source game that i don't think is dependent on glibc is `xonotic`, but it also runs fine.

It is probably ewmh. I'll try to figure it out on my own since i'm probably one of the few that want to run tf2+a wm with no ewmh.

I'll try to be back with results(and a patch if needed) as soon as possible(might take up to a week).

**Comment by tjtf2** [comment]
Well i asked around and people are saying that the wm shouldn't matter, though i'm seeing that that is not the case.

I might not be able to write the patch, i yet don't know if ewmh is really the cause of this and it's also quite difficult to implement ewmh support.

**Comment by tjtf2** [comment]
Tomorrow, i'm going to slowly start removing stuff from dwm until fullscreen games break, then i'll know exactly what to add to my patch

**Comment by tjtf2** [comment]
Well i'm making progress!

I've removed ewmh support from dwm and it seems to have broken tf2, well now i know that i was indeed right with my assumption that ewmh was the problem,  now i got to figure out what part of ewmh i need to implement and also how to implement it.
