### ISSUE TITLE
Can't apply rounded corners patch

### ISSUE THREAD

**Issue by dab** [dylanaraps/sowm#17]
Hi there, trying to apply patch for rounded corners without success:

```
$ git apply patches/sowm-rounded-corners.patch
error: patch failed: sowm.c:201
error: sowm.c: patch does not apply
```

Any easy solution available?

**Comment by tjtf2** [comment]
Try using the latest release: 0.3(i think)

Patches aren't up to date with the git versions.

If you are using the latest git because of the mod bug, i guess you won't have round corners until the next release(or in the case that on sunday the next release isn't out yet, i'll convert all of the patches to work on the latest git version for sunday)
