### ISSUE TITLE
Have status bars span across all workspaces

### ISSUE THREAD

**Issue by manfromth3m0oN** [dylanaraps/sowm#25]
Is there some way to have a statusbar (e.g. polybar) span across all workspaces like the way it works in i3. If this is not currently implemented could someone please give me some pointer for making a patch to allow this.
Thanks
~ M

**Comment by clusterF** [comment]
Hi dylan, not sure if this will be of any help but when i use lemonbar with below config in sowm it spans accross all workspaces only if set with -d and -p flags i think.

`conky | lemonbar -g x22 -B "#1F1F1F" -F "#00FF00" -pb -f "-xos4-terminus-bold-*-normal-*-12-120-72-72-*-60-iso8859-16" -d -p  &
`

`-d  Force docking without asking the window manager. This is needed if the
           window manager isn't EWMH compliant.
`
`-p  Make the bar permanent, don't exit after the standard input is closed.
`

**Comment by Leon-Plickat** [comment]
I think this issue can be closed.

Bars and other desktop widgets will never behave perfectly, because they expect the WM to implement (and respect) EWMH. As proudly proclaimed in the README, EWMH not being implemented is a feature of this WM.

As a workaround, windows with redirect-override should be completly ignored by the WM and therefore appear on every workspace. AFAIK lemonbar, polybar and conky support redirect-override for their windows, so you can use those as a bar.
