### ISSUE TITLE
Bug in handlebar patch

### ISSUE THREAD

**Issue by arnolddinkla** [dylanaraps/sowm#31]
Easiest described by saying if you have 2 terminal windows open and move one of them over the other with the handlebar, they will follow each other and sometimes swap focus. Also if they are a different size the larger window will shrink to the size of the smaller one. Does not happen in unpatched sowm.

**Comment by dylanaraps** [comment]
Ping @Leon-Plickat

**Comment by Leon-Plickat** [comment]
Ah, I encountered that "feature" as well about a week ago but did not yet have had the time to fix it.

The problem is actually simple: When dragging the handlebar, your pointer moves faster than it or the window you are dragging, typical for X. The issue is that during dragging you can still focus windows simply by moving the mouse over them. Sowm believes that the currently focused window is always the one being dragged, so the freshly focused window will "steal" the titlebar and drag operation. Since internally this operation uses `XMoveResizeWindow()` instead of just `XMoveWindow()`, the new accidental focus reshapes itself into the dimensions of the previous focus.

You can expect a fix in the next five days.

**Comment by arnolddinkla** [comment]
Thanks guys

**Comment by Leon-Plickat** [comment]
See #39
