### ISSUE TITLE
i need some help with sowm!

### ISSUE THREAD

**Issue by aldorgan** [dylanaraps/sowm#67]
I have compiles sowm on Debian and installed it with sudo make install, but i can't get it to show up in Lightdm or GDM as a option? How can i do that sorry for my lack of skills.

I could't find any other forum/reddit to write this on.

**Comment by DavidHusicka** [comment]
Here's my solution: https://github.com/dylanaraps/sowm/pull/66

It works on my Ubuntu but wait a little with it because I had problem with sowm losing connection with X11 server. It has something to do with GDM/Gnome. I have hot-fix which works and I'll publish it ASAP. I'll maybe later also make proper fix for this. This may not happen but most likely will since I use it as my daily driver now. Please, pay attention to PRs and wait for the fix. If it works properly even without the fix, good for you. 

When I'll have the hot fix in PRs as a patch, I'll comment here so you will know.

**Comment by aldorgan** [comment]
> Here's my solution: #66
> 
> It works on my Ubuntu but wait a little with it because I had problem with sowm losing connection with X11 server. It has something to do with GDM/Gnome. I have hot-fix which works and I'll publish it ASAP. I'll maybe later also make proper fix for this. This may not happen but most likely will since I use it as my daily driver now. Please, pay attention to PRs and wait for the fix. If it works properly even without the fix, good for you.
> 
> When I'll have the hot fix in PRs as a patch, I'll comment here so you will know.

Thank you it works now :) i have not seen any problem yet though, so maybe i'm lucky.
